import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.sass";
import StoreProvider from '@/lib/redux/provider';
import ToastList from "@/components/toast/list";
import Menu from "@/components/menu/server";
import Style from "@/app/style.module.sass";
import CallModal from "@/components/call/modal";
import 'bootstrap/dist/css/bootstrap.min.css'
import "fontawesome-free-v6/css/all.css"

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body>
        <StoreProvider>
            <CallModal />
            <ToastList/>
            <div className={Style.template}>
                <div className={Style.center}>
                    <div className={Style.content}>
                        {children}
                    </div>
                    <div className={Style.footer}>
                        <Menu />
                    </div>
                </div>
            </div>
        </StoreProvider>
        </body>
        </html>
    );
}